language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 12

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g serverless
  - npm install -g mocha

script:
    - npm install
    - npm test