language: node_js

os:
  - linux

node_js:
  - 12
  - 14
  - 16

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g serverless@3.19.0

script:
    - npm install
    - npm test